### ISSUE TITLE
Products: Complete Documentation on MUF

### ISSUE THREAD

**Issue by joeschoonover** [NOAA-SWPC/GSMWAM-IPE#1]
We have opened a document to begin filling in details on this product.

 Ideally, we should have some background information that explains what this product is and why it would be useful. We should indicate intended customers that would benefit from SWPC supporting this product. 

Additionally, we should document, with references, how we are calculating MUF and report on other diagnostics/indexes that we can derive from forecasts of MUF.

The document can be found [here](https://docs.google.com/document/d/1IBJbWB0UH5J3b2UpSBbsaNLqt-DUsNaJZma3kp3-rC0/edit?usp=sharing)

**Comment by twfang** [comment]
MUF = M3000*foF2 This is what is implemented in CTIPe now. 
  1. Calculate M3000 following Shimazaki improved by Bradley, P. A., and J. R. Dudeney (1973)
  2. We do not have FoE and approximate it based on Local Time
  3. Calculate MUF(3000)
  loctime = Local Time (0-23:59 corresponding to the longitude) This changes with UT!
  nlongs = number of longitudes
  nlats = number of latitudes
 
 for i=0, nlongs do begin
  for j=0, nlats do begin
    M3000(i,j) = 1490./(hmF2(i,j) + 176.)
    M3000(i,j) = M3000(i,j) - .6*sin(3.1415/12.*(loctime(i) - 5.))
    MUF3000(i,j) = M3000(i,j)*sqrt(nmF2(i,j))/(1.11355287e+5) 
     
  endfor  ; j=0,90
 endfor   ;i=0,20


Shimazaki, T. (1955), World?wide variations in the height of the maximum electron density of the ionospheric F2 layer, J. Radio Res. Lab. Jpn., 2( 7), 85– 97.

Bradley, P. A., and J. R. Dudeney (1973), A simple model of the vertical distribution of electron concentration in the ionosphere, J. Atmos. Terr. Phys., 35, 2131– 2146.

**Comment by twfang** [comment]
Current CTIPe MUF product is updated at SWFO every 10 mins. With our NmF2/hmF2 every 3 min, we can easily get MUF calculated. I will try to plot some of them out once we get our hmF2 fixed.

**Comment by twfang** [comment]
More validation is required for the MUF product. New issue will be opened when we redo the validation.
