### ISSUE TITLE
Bringing in Data from WCOSS to SWPC

### ISSUE THREAD

**Issue by twfang** [NOAA-SWPC/GSMWAM-IPE#11]

**Comment by twfang** [comment]
George has fixed the data flow and plot from WCOSS phase 3 to SWPC. The plot is currently based on Houjun's real-time run. 
https://www.swpc.noaa.gov/products/wam-ipe

Various things that have been implemented:
1. running on wcoss3 (previously no connectivity between wcoss3 and gmillwardlx)
2. An overambitious setup to the graphics - too many assumptions about what 'ops' would be doing - now I just plot out Houjun's latest files - which does the trick for now
3. Houjun's TEC NmF2 numbers were 'the other way round' [ie, i,j instead of my j,i] - trivial but needed sorting
4. Anomaly plot (diff to 10-day average) still needs re-jigging - not working at present - but the fix should be done today

**Comment by gmillward** [comment]
4 above ^^ (anomaly plots) now sorted, not fully tested, but 'it works' - well enough for now
