### ISSUE TITLE
List for WAM and IPE parameters and factors

### ISSUE THREAD

**Issue by twfang** [NOAA-SWPC/GSMWAM-IPE#17]
Let's start to build a list of parameters or factors that need to be kept in namelist/input files, so that they can be easily changed once the model goes operation. Once we have a completed list, we can see how to get them out and how to organize them in a reasonable way.

**Comment by ZhuxiaoLi66** [comment]
Tim and I are considering to include Kt_eddy (eddy mixing coefficient, in idea_tracer.f) and JH_fac (Joule Heating factor, in idea_ion.f) in namelist files for WAM.

**Comment by twfang** [comment]
For IPE, we need to bring out the following parameters and switches. 
1. Switch for the empirical model or self-consistent dynamo solver (already in config file)
2. Switch for the high-latitude empirical model (Heelis or Weimer), currently uses "potential_model" in dynamo/dynamo_module.f

In IPE_Plasma_Class.F90
transport_highlat_lp
perp_transport_max_lp
HPEQ
colfac/COLFACX (O-O+ collision frequency)

**Comment by ZhuxiaoLi66** [comment]
In WAM, we added JH0, JH_tanh, JH_semiann, JH_ann to the namelist for Joule Heating calculation (idea_tracer.f). 
Added skeddy0, skeddy_semiann, skeddy_ann for the calculation of the effect of eddy mixing on Species (idea_ion.f).
Added tkeddy0, tkeddy_semiann, tkeddy_ann for the calculation of the effect of eddy mixing on 
Temperature (idea_dissipation.f).

**Comment by twfang** [comment]
https://docs.google.com/document/d/1vA-rTabMwaCkB1Efs0TRe3CIvpbwboRY_o4SY_v7Hgo/edit?usp=sharing

Please take a look at the list and see if anything else needs to be added.

**Comment by timfullerrowell** [comment]
I'll study.

One thing after quick look, perhaps reference level for O/N2 calculation.

Tim
