### ISSUE TITLE
Adding WAM parameters and factors

### ISSUE THREAD

**Issue by ZhuxiaoLi66** [NOAA-SWPC/GSMWAM-IPE#20]
The test work to add WAM (at first) parameters and factors to namelist is undergoing.

**Comment by ZhuxiaoLi66** [comment]
A test branch named wam_namelist_test has been pushed to NOAA-SWPC/GSMWAM-IPE. 
will be updated with the code 
 adding JH0, JH_tanh, JH_semiann, JH_ann to the namelist for Joule Heating calculation (idea_tracer.f).
Added skeddy0, skeddy_semiann, skeddy_ann for the calculation of the effect of eddy mixing on Species (idea_ion.f).
Added tkeddy0, tkeddy_semiann, tkeddy_ann for the calculation of the effect of eddy mixing on
Temperature (idea_dissipation.f).

**Comment by twfang** [comment]
@ZhuxiaoLi66 do you have any updates on this issue? Are they all done?

**Comment by ZhuxiaoLi66** [comment]
the current code branch finished the adding of all the above WAM parameters, will discuss and confirm a little bit more with Tim about other parameters.
