### ISSUE TITLE
Workflow (SWIO-specific) refresh

### ISSUE THREAD

**Issue by akubaryk** [NOAA-SWPC/GSMWAM-IPE#22]
branch `workflow_refresh` has been created to help address lingering issues from #21.

There has been a minor overhaul in namelist and resource file writes, extracting their contents from exglobal and putting them into `scripts/compsets/parm` (PARMDIR) for either linking into the RUNDIR, or rewriting into the RUNDIR by use of `envsubst`.

Use of SWIO is now configurable by setting SWIO=.true. or .false.

There is a default configuration for SWIO=.true. for both standaloneWAM and WAM-IPE. If the user wishes to change this configuration, they can alter PARMDIR/nems.configure.${MODE}_io and create or alter the appropriate resource file in the parm directory. Additionally, the user should set `SWIO_MODELS` (by default for WAM-IPE, `SWIO_MODELS="IO AIO"`), and then for each IO model, `MODEL_PREFIX` and `MODEL_CADENCE` (e.g. `IO_PREFIX=ipe` and `AIO_PREFIX=wam`, and `IO_CADENCE=AIO_CADENCE=180`). This should match with the runSeq and output prefix listed in nems.configure and the SWIO resource file respectively, for purposes of linking the output from RUNDIR to ROTDIR. I debated a few ways to extract these values automatically from nems.configure and the resource files, but couldn't settle on anything that was appropriately simple.

Further tasks that need to be completed for resolution of this issue:

1. Determine what needs to be exported from each model and at what cadence; identify variables that should be calculated from the export state prior to output by SWIO. Establish how to add model fields to the export state.
2. Extend the med.rc above 800km. [from @twfang]
2. Determine an appropriate default runSeq for each mode (multiple components per model?).
3. Have SWIO components output at the final model timestep (i.e. a one-hour run with `AIO_CADENCE=3600` should produce output).

Anything else, please add.

**Comment by twfang** [comment]
One more thing is added here. 
1. Determine what needs to be exported from each model and at what cadence; identify variables that should be calculated from the export state prior to output by SWIO. Establish how to add model fields to the export state.
**2. Extend the med.rc file to above 800 km.** 
3. Determine an appropriate default runSeq for each mode (multiple components per model?).
4. Have SWIO components output at the final model timestep (i.e. a one-hour run with AIO_CADENCE=3600 should produce output).

**Comment by rmontuoro** [comment]
Commit b4e00d9 addresses item 2. Additional settings will be included in the `med.rc` file to automatically use all vertical levels from the IPE mesh to build the intermediate 3D mesh in the SWPC mediator.

**Comment by akubaryk** [comment]
Commit 0d424388 fixes some filename mistakes I had made when linking SWIO output from the RUNDIR to the ROTDIR, but I've discovered that the soft links are destroyed and the file is written in-place to the RUNDIR. Tracing this back through SWIO and COMIO, I see that NF90_CLOBBER is being used when opening output files (mode "c") -- I'm not exactly sure why this is destroying the symlink, though, because the standard NetCDF interface (nf90_create) doesn't do this. I wrote test programs with PNetCDF 1.10.0 and NetCDF 4.7.0 and confirmed this behavior: you can `cp -r /scratch1/NCEPDEV/swpc/Adam.Kubaryk/nonsense/pnetcdf_clobber` to your own space and run the test.sh script to confirm that ptest.nc is written in place, while test.nc will be properly linked to test_output.nc.

I stopped a run after the first SWIO output timestep for the sake of completeness: /scratch1/NCEPDEV/stmp4/Adam.Kubaryk/iotest

**Comment by ZhuxiaoLi66** [comment]
I did a test run with the following setting in scripts/compsets/iotest_config_new
export MODE="WAM-IPE"
export SWIO=".true."
export SWIO_MODELS="IO AIO"
export IO_PREFIX="ipe"
export AIO_PREFIX="wam"
export IO_CADENCE=360
export AIO_CADENCE=360
in /scratch1/NCEPDEV/stmp4/Zhuxiao.Li/iotest_prefix (ROTDIR)
I have got the ipe*nc and the gsm*nc output in 180 secs cadence with good file size. The wam*nc output are in 360 secs cadence as I set, the files has soft links to the same name files in RUNDIR, which haven't been produced yet. 
I downloaded the tip workflow_refresh branch and configued it by 'gmake -j app=coupledWAM_IPE_SWIO build'.

**Comment by akubaryk** [comment]
Thanks for doing this test @ZhuxiaoLi66. You also need to change the runSeq in the appropriate parm/nems.configure* file to get the SWIO output at appropriate cadence; this part is not handled for you for now; in the future I may write a Python program to handle the runSeq write from such cadence or timestep variables, but it would be a low priority for now.

**Comment by ZhuxiaoLi66** [comment]
@akubaryk got it, thanks.

**Comment by ZhuxiaoLi66** [comment]
@akubaryk So I need to change the runSeq in both parm/nems.configure.WAM-IPE_io and nems.configure.WAM-IPE files for coupling case?

**Comment by akubaryk** [comment]
No, nems.configure.WAM-IPE does not contain the SWIO components; the nems.configure files without the _io suffix are used when SWIO=.false., and the _io files are used when SWIO=.true.

**Comment by ZhuxiaoLi66** [comment]
got it, thanks.

**Comment by ZhuxiaoLi66** [comment]
It doesn't change the default cadence when I do the following in parm/nems.configure.WAM-IPE_io:
runSeq::
 @360.0
  @$coupling_interval_slow_sec
    ATM -> MED :remapMethod=redist
    MED
    MED -> IPM :remapMethod=redist
    @$coupling_interval_fast_sec
      ATM
    @
    IPM
    AIO
    ATM -> AIO
    IO
    IPM -> IO
  @
 @
::

**Comment by twfang** [comment]
I think you made a small mistake in the loop.

Try this one

runSeq::
@360.0
@$coupling_interval_slow_sec
ATM -> MED :remapMethod=redist
MED
MED -> IPM :remapMethod=redist
@$coupling_interval_fast_sec
ATM
@
IPM
@
AIO
ATM -> AIO
IO
IPM -> IO
@

**Comment by twfang** [comment]
This worked for me when I tested Rafaelle's pull request.

**Comment by akubaryk** [comment]
@twfang's is correct. If you don't move the IO component calls into the outer loop, they'll execute in the inner loop with ATM->MED, MED, MED->IPM, and IPM.

**Comment by ZhuxiaoLi66** [comment]
I see, thanks.

**Comment by rmontuoro** [comment]
Commit 40220a1b updates SWIO to write output at the last time step, addressing item 4.

**Comment by twfang** [comment]
Raffaele, thanks for getting this fixed!
