### ISSUE TITLE
V&V on Ops. WAM-IPE Aug. 2020

### ISSUE THREAD

**Issue by ZhuxiaoLi66** [NOAA-SWPC/GSMWAM-IPE#41]
The Ops. WAM-IPE storm validations will be conducted to verify the output of 3D neutral (might include plasma later) fields (U, V, W, T, O, O2, N2, mass density, H, He) and 2D neutral& plasma fields ( TEC, O/N2) from the tip operational WAM-IPE, against the corresponding observational dataset, and also the corresponding former runs of WAM-IPE.
The storm case will be the St. Patrick storm of 2015 (Mar.16-21 2015). 
Will includes (not limited to) the following validations,
a) The vertical integral O/N2 (at pressure levels) against the track-by-track 24hrs GUVI data during Mar.16-21 2015, against the corresponding former runs. 
b) The thermosphere neutral total mass density (at about 400km) against point-to-point along with the satellite trail data of GRACE.
c) TEC against the output & data of GloTEC & MIT.
d) Tides analysis based on the hourly output of an annual run of WAM.
...

**Comment by twfang** [comment]
Lastest run with WAM-IPE v1.0 in 3 min and 5 min timesteps can be found in the following link. 
https://drive.google.com/drive/u/1/folders/1qttFQybCAA9joRIM_Or2RHlblTKc3f-a

**Comment by twfang** [comment]
Some preliminary ionospheric validation by Tim can be found here. 
https://drive.google.com/file/d/1GagCjj0bMhBvXlJ-mWGFCGcBRL4Xv6y6/view

**Comment by ZhuxiaoLi66** [comment]
The WAM-IPE 2015 St. Patrick's (Mar.16-Mar.21) storm run by the latest operational version has been conducted with the IC files from the latest updated-WAM-physics runs. The output cadence is 3mins for both WAM and IPE in stmp4, hourly in stmp2. 
For some unknown reason (maybe need further investigation by Raffaele), we only have gotten the 3mins output from both WAM & IPE for the last restart run (3runs in line for 6 days), which means we have 3mins output for 20150320 & 20150321 for now in the following directory, 
Hera:/scratch1/NCEPDEV/stmp4/Zhuxiao.Li/coupled_20150316_tip_validation_3mins. 
The hourly output of WAM & IPE for the total 6 days (20150316-20150321) are on the directory below:
/scratch1/NCEPDEV/stmp2/Zhuxiao.Li/coupled_20150316_tip_validation_3mins

I already submitted a coupling simulation with 6 days in one run for the full 3mins output dataset with the latest operational version. 
While the output issue for the restart runs still need to be figured out for future application.

**Comment by ZhuxiaoLi66** [comment]
The following plot is the O/N2 validation for the hourly output of the current storm run on 20150317(most intense storm time), 
against the GUVI tracks data. That means the corresponding WAM panel in the following plot is a track-by-track plot on 20150317 with hourly WAM output.
![O_N2_20150317_WAM_hrly_GUVI_tracks](https://user-images.githubusercontent.com/22546571/89818524-24fc7400-db07-11ea-8ce1-50059d9c3f8d.png)

**Comment by ZhuxiaoLi66** [comment]
The following is the corresponding validation for WAM 3mins NetCDF output in a WAM former run back to Dec. 2019. 
It is expected that the 3mins output from SWIO on 20150317 by the current operation should be very close to this result, 
since the physics & compilers. etc.  haven't been changed since then.
 
![O_N2_20150317_WAM_3mins_GUVI_tracks_old](https://user-images.githubusercontent.com/22546571/89819626-fb444c80-db08-11ea-8e06-ac65f0ab96eb.png)

**Comment by ZhuxiaoLi66** [comment]
This plot is a similar one with the plot above, except based on the 3mins output from SWIO (instead of the WAM direct netcdf-output for the above plot) of the tip operational GSMWAM-IPE. The WAM direct output represent the original output from WAM.  After comparison, we can found that the results are close, while still different in some fine features. 

![O_N2_20150317_WAM_3mins_GUVI_tracks_ops_tip](https://user-images.githubusercontent.com/22546571/89940796-4f1d6700-dbd7-11ea-9eac-f768d128986e.png)

**Comment by ZhuxiaoLi66** [comment]
Results of b) and c) will come out soon.

**Comment by ZhuxiaoLi66** [comment]
The SWIO output (for WAM) of the thermosphere total mean mass at 400km (iss_mass_density) for 2015 St. Patrick storm has been applied for the total mean mass validation of WAM against the corresponding GRACE orbit-by-orbit observational data. 
The results are shown in the following plots. 
[Unscaled GRACE 2015 March 16_19 400km_den_iss_lonlat_2.docx](https://github.com/NOAA-SWPC/GSMWAM-IPE/files/5475298/Unscaled.GRACE.2015.March.16_19.400km_den_iss_lonlat_2.docx)
![DEN_iss_validation_20150316-0319_1](https://user-images.githubusercontent.com/22546571/97873727-479cc400-1cd5-11eb-9096-dbafd8a4b3f0.png)
![DEN_iss_20150316-0319_2](https://user-images.githubusercontent.com/22546571/97873745-4ec3d200-1cd5-11eb-823b-27279e5ee8be.png)
![DEN_iss_validation_20150316-0319_3](https://user-images.githubusercontent.com/22546571/97873796-5aaf9400-1cd5-11eb-8d02-94af11b1145f.png)

**Comment by ZhuxiaoLi66** [comment]
The bias of the WAM output from GRACE data at the intense storm time (12UT Mar.17 - 6UT Mar.18) is larger than the one in the former validation with the interpolated multiple fixed height WAM output as shown in the following plots. 
![DEN_WAM_validation_20150316-0319_original](https://user-images.githubusercontent.com/22546571/97874790-c6dec780-1cd6-11eb-93a9-ba7fdb5d1a22.png)

**Comment by ZhuxiaoLi66** [comment]
The difference is considered due to the varying height (not fixed height) along the orbit of GRACE. 
Based on Martin's statement,  minimum height: 392.29km, maximum height: 431.74km. 
The plan now is that the total mean mass dataset will be remade with the original SWIO output of thermosphere_mass_density, the interpolated fixed height data with height 380km-440km will be applied to do the validation again.

**Comment by ZhuxiaoLi66** [comment]
The dataset of total mean mass with a vertical dimension of fixed height has been remade based on the original SWIO output of thermosphere_mass_density. 
The new validation results (show below) against the along-orbit GRACE data looks very consistent with our former base validation results. it verified that the SWIO output in the WAM-IPE operational version keeps the consistent physics feature in neutral total mass during storm time with our base version.

![WAM_den_20150317_GRACE_operation](https://user-images.githubusercontent.com/22546571/98572308-b8faea80-2272-11eb-90cb-5c473520c1c3.png)
![WAM_den_20150317_GRACE_operation_2](https://user-images.githubusercontent.com/22546571/98572323-bbf5db00-2272-11eb-8330-134399fce7dd.png)
![WAM_den_20150317_GRACE_operation_3](https://user-images.githubusercontent.com/22546571/98572331-bef0cb80-2272-11eb-9851-c4c0c5685424.png)

**Comment by ZhuxiaoLi66** [comment]
Attached is the original word file for the latest validation. 
[Unscaled GRACE 2015 March 16_19 SWIO_opr_valid_7levs.docx](https://github.com/NOAA-SWPC/GSMWAM-IPE/files/5513281/Unscaled.GRACE.2015.March.16_19.SWIO_opr_valid_7levs.docx)

**Comment by ZhuxiaoLi66** [comment]
![TEC_MIT_2013030600](https://user-images.githubusercontent.com/22546571/100658284-06b3c180-330c-11eb-8bac-803bbd88a0f5.png)

**Comment by ZhuxiaoLi66** [comment]
The above plot is for the entire day of Mar.6 of 2013. 
The following plots are the on averaging for 20mins range on 20130306 00:20:00-00:40:00 and the corresponding one downloaded from CEDAR website. The difference due to the latter one is rebined into 3deg by 3 deg and the area calculation is weighted by cosin(lat). 
![MIT_TEC_2013030600_NCL](https://user-images.githubusercontent.com/22546571/102116424-2cf05b80-3dfa-11eb-931d-290c674b759f.png)
![TEC_MIT_2013030600_cedar](https://user-images.githubusercontent.com/22546571/102116616-7476e780-3dfa-11eb-91b7-9d96cb6e2af0.png)

**Comment by ZhuxiaoLi66** [comment]
![TEC_MIT_20130306-15_0UT_2deg](https://user-images.githubusercontent.com/22546571/103569157-0c10a880-4e84-11eb-9a70-456877be4f76.png)

**Comment by ZhuxiaoLi66** [comment]
![TEC_0UT_WAM_20130306-15](https://user-images.githubusercontent.com/22546571/103569347-5a25ac00-4e84-11eb-98a6-5f1484196d69.png)

**Comment by ZhuxiaoLi66** [comment]
With the MIT GPS TEC observational data, we are trying to estimate the WAM TEC bias based on the following formula.   

bias = exp ( (SUM over N values of orbit timeseries ( ln (TEC(model) / TEC(obs) ) ) ) / N )

![image](https://user-images.githubusercontent.com/22546571/104218673-4e913280-53fa-11eb-9633-ea283183c880.png)

**Comment by timfullerrowell** [comment]
The first step is to develop the methodology using the observed (MIT maps) and modeled TEC for the period from March 6-15th. We will be using the expression for TEC bias as the metric:

bias = exp ( SUM over N values of ( ln (TEC(model) / TEC(obs)  ) ) / N )

1. Firstly, choose one UT time interval of observed TEC from the MIT maps, with N observations at a set of lat/long locations
2. Extract the TEC from the set of WAM-IPE simulations with varying eddy mixing of composition at the same time 
3. Interpolate WAM-IPE TEC to the same set of N values at the same lat/long as the observations (maybe averaged over the data time interval)
4. Calculate the bias using above expression and find the WAM-IPE map with the minimum bias
5. Repeat for all UTs for a typical day, and over the 10 day period to see if the results are consistent (the data values will cover different regions during the UT day so the results might not be consistent) 

If the results are not consistent, try dividing up the regions a) day/night separately, b) low latitude to target EIA peaks in TEC, c) regions around the peaks +/-10degrees N/ and E/W, etc. until a reliable consistent is established

Repeat with Glo-TEC. 

Once a reliable methodology has been developed. Set up a system to routinely track TEC bias on a weekly basis between WAM-IPE and Glo-TEC. For each week, determine if there is an increasing trend in the TEC bias and determine if an adjustment in the eddy mixing in the operational version is required.

**Comment by ZhuxiaoLi66** [comment]
![image](https://user-images.githubusercontent.com/22546571/104359218-9e402e80-54cc-11eb-9388-305be308a74d.png)

**Comment by ZhuxiaoLi66** [comment]
![image](https://user-images.githubusercontent.com/22546571/104359325-bfa11a80-54cc-11eb-84cc-c2875396dba8.png)

**Comment by ZhuxiaoLi66** [comment]
Tim, the above is the TEC comparison at 12UT between WAM and MIT GPS data. Thanks.

**Comment by timfullerrowell** [comment]
Something doesn't look right. Is the MIT TEC plat a particular day, or an
average from 6-15th?

**Comment by ZhuxiaoLi66** [comment]
the MIT TEC is an average for Mar.6-15th.

**Comment by timfullerrowell** [comment]
Do you have access to the MIT plots on particular days for that period, to
make sure we have interpreted the format correctly (e.g., longitude vs LT).
I just tried to go to the MIT website and it said there was a Python
problem. Are you able to get in.

**Comment by ZhuxiaoLi66** [comment]
I also can't access the data plots (stuck in the middle of somewhere). I Will give a retry tomorrow or just send an email to Bill Rideout to report this tonight.

**Comment by ZhuxiaoLi66** [comment]
The time average (Mar.6-15 2013) MIT TEC becomes more consistent with the WAM output after I interpolated the data onto the IPE output grid (more reasonable grid). the following is the improved MIT TEC at 12 UT. 
![TEC_20130306-15_12UT_MIT_grid](https://user-images.githubusercontent.com/22546571/105080258-d22bce80-5a4d-11eb-8a96-0e1845966d74.png)

**Comment by ZhuxiaoLi66** [comment]
The WAM TEC output biases at specific UT with different eddy0 values have been calculated based on the following formula: 
![image](https://user-images.githubusercontent.com/22546571/105080485-1b7c1e00-5a4e-11eb-8b42-9b864f1a91b2.png)
The output of 20130306 was calculated as a test, the results are shown in the following plot. 
![bias_M_O_keddy0_UT_20130306_1](https://user-images.githubusercontent.com/22546571/105081606-a14c9900-5a4f-11eb-85fd-1b24e0e80693.png)

**Comment by ZhuxiaoLi66** [comment]
the TEC bias averaged during Mar.6-15 2013 has been calculated. The pattern is very consistent with the pattern of day1 (Mar.6) and each of the other days. The following plots are the mean TEC bias and the TEC bias for several other days. 

![bias_M_O_keddy0_UT_20130306-15_avg](https://user-images.githubusercontent.com/22546571/105536169-28e31380-5cad-11eb-9d2c-c70eaba51a67.png)

**Comment by ZhuxiaoLi66** [comment]
![bias_M_O_TEC_20130307](https://user-images.githubusercontent.com/22546571/105536206-36989900-5cad-11eb-8fef-0954ef91f903.png)
![bias_M_O_TEC_20130310](https://user-images.githubusercontent.com/22546571/105536239-41ebc480-5cad-11eb-9e9c-9a6519f2816c.png)
![bias_M_O_TEC_20130313](https://user-images.githubusercontent.com/22546571/105536257-487a3c00-5cad-11eb-9a6d-8f0f0c5b05f1.png)
![bias_M_O_TEC_20130315](https://user-images.githubusercontent.com/22546571/105536275-4f08b380-5cad-11eb-9cc5-d3a84b54efad.png)

**Comment by ZhuxiaoLi66** [comment]
The following is the average MIT TEC & coverage at different UT. 
![TEC_20130306-15_0UT_MIT_grid](https://user-images.githubusercontent.com/22546571/105755136-1f091c80-5f08-11eb-886e-06111e8e38ab.png)
![TEC_20130306-15_06UT_MIT_grid](https://user-images.githubusercontent.com/22546571/105755155-25979400-5f08-11eb-8489-09203c74e42f.png)
![TEC_20130306-15_12UT_MIT_grid](https://user-images.githubusercontent.com/22546571/105755177-2c260b80-5f08-11eb-9293-46e53a88f5e5.png)
![TEC_20130306-15_18UT_MIT_grid](https://user-images.githubusercontent.com/22546571/105755197-321bec80-5f08-11eb-9e86-8003d8885038.png)

**Comment by ZhuxiaoLi66** [comment]
![image](https://user-images.githubusercontent.com/22546571/105755387-7909e200-5f08-11eb-8445-821ec5794d31.png)

**Comment by ZhuxiaoLi66** [comment]
The following is the MIT TEC interpolated onto WAM-IPE output grid for the bias calculation. 
![TEC_MIT_interpolated_20130306](https://user-images.githubusercontent.com/22546571/105771176-65b54180-5f1d-11eb-89f3-017fe43c233f.png)

**Comment by ZhuxiaoLi66** [comment]
The following is the GloTEC data example from the latest 20210103-0120 run.  The data is with quality_flag>=3, good. 

![GloTEC_20210108_3flag](https://user-images.githubusercontent.com/22546571/106519678-e71a5000-6498-11eb-930c-edf251678f50.png)
![GloTEC_20210112_3flag](https://user-images.githubusercontent.com/22546571/106519696-ed103100-6498-11eb-9c33-9fe94a93cd62.png)

**Comment by ZhuxiaoLi66** [comment]
The NCL code to calculate the model bias (WAM/GloTEC) is ready, the following is the code test to compare the GloTEC data (20210103-20210112) and WAM data (20130306-0315). Please notice that the time periods of the two data do not match, so it is just a code test.
 
![bias_M_O_TEC_WAM_GloTEC_test](https://user-images.githubusercontent.com/22546571/106521148-087c3b80-649b-11eb-99fc-c900d2b8f49b.png)

**Comment by timfullerrowell** [comment]
Thanks Zhuxiao.
Interestingly the UT trend is similar to MIT.
Are the MIT maps for the January period also available?
Tim

**Comment by ZhuxiaoLi66** [comment]
The following is the TEC maps example of GloTEC & MIT in January of 2021. 
 
![TEC_low2hi_GloTEC_MIT_20210103](https://user-images.githubusercontent.com/22546571/107281580-17249e80-6a17-11eb-9383-0a73fa30fec2.png)
![TEC_low2hi_GloTEC_MIT_20210104](https://user-images.githubusercontent.com/22546571/107281594-1b50bc00-6a17-11eb-990e-406afd357b22.png)

![TEC_low2hi_GloTEC_MIT_20210108](https://user-images.githubusercontent.com/22546571/107281728-463b1000-6a17-11eb-88c5-cd166e5f8d5b.png)

**Comment by ZhuxiaoLi66** [comment]
The GloTEC TEC during this period is much larger compared with MIT TEC, at a factor close to 2, the reason is investigating. The following plots show the TEC ratio (MIT/GloTEC) at different UT by two different interpolation ways on the observational data.
![bias_MIT_GloTEC_11days_24UT_avg_low2hi](https://user-images.githubusercontent.com/22546571/107282218-eb55e880-6a17-11eb-9ce1-4c4643fff321.png)
![bias_MIT_GloTEC_11days_24UT_avg_new](https://user-images.githubusercontent.com/22546571/107282249-f4df5080-6a17-11eb-8348-2b0c4ea9a754.png)

**Comment by ZhuxiaoLi66** [comment]
After excluding the area with TEC <10 in the bias calculation of MIT/GloTEC and WAM/MIT. We can see the bias between MIT&GloTEC is improved to close to 1. and the WAM/MIT is improved by becoming more converging in the diurnal variation. 
![bias_MIT_GloTEC_11days_24UT_avg_low2hi_mask_TEC_10](https://user-images.githubusercontent.com/22546571/108751879-063c5880-7500-11eb-8094-9f048852be21.png)
![TEC_bias_WAM_GloTEC_low2hi_mask_10TEC](https://user-images.githubusercontent.com/22546571/108751889-0b010c80-7500-11eb-96a6-9c7648ee29c2.png)

**Comment by ZhuxiaoLi66** [comment]
With the WAM-IPE output from pseudo-operational (free) runs during the period of Jan.3-Jan.20, 2021, the WAM-IPE biases of TEC against GloTEC and MIT GPS data respectively for that period have been investigated. The results are shown below. 
![TEC_bias_IPE_GloTEC_low2hi_mask_10TEC_20210103_0113](https://user-images.githubusercontent.com/22546571/109541685-4f048c00-7a81-11eb-9070-5697d59f8fad.png)
![TEC_bias_IPE_MIT_low2hi_mask_10TEC_20210103_0113](https://user-images.githubusercontent.com/22546571/109541713-575cc700-7a81-11eb-9df4-53775dcd3a7c.png)

**Comment by ZhuxiaoLi66** [comment]
The difference of TEC between GloTEC & MIT is under investigation.

**Comment by ZhuxiaoLi66** [comment]
![TEC_bias_IPE_GloTEC_low2hi_mask_10TEC_20210103_0119](https://user-images.githubusercontent.com/22546571/110365448-4b817f80-8002-11eb-9a0e-f7f7eb88fc3f.png)
![TEC_bias_IPE_MIT_low2hi_mask_10TEC_20210103_0119](https://user-images.githubusercontent.com/22546571/110365469-52a88d80-8002-11eb-8978-5019a58471b3.png)

**Comment by ZhuxiaoLi66** [comment]
![TEC_bias_WDAS_IPE_MIT_low2hi_mask_10TEC_20200801-0818](https://user-images.githubusercontent.com/22546571/112527191-64ab5f80-8d68-11eb-8879-3245bc661272.png)
![TEC_map_WDAS_IPE_MIT_low2hi_20200802](https://user-images.githubusercontent.com/22546571/112527236-73921200-8d68-11eb-8071-037d054412d3.png)
![TEC_map_WDAS_IPE_MIT_low2hi_20200814](https://user-images.githubusercontent.com/22546571/112527247-77259900-8d68-11eb-8a88-99c2e70d942d.png)
