### ISSUE TITLE
tidal anaysis

### ISSUE THREAD

**Issue by ZhuxiaoLi66** [NOAA-SWPC/GSMWAM-IPE#43]
This project introduces the main results on the WAM tidal analysis based on the WAM output 3 years ago,  and its comparison with  the main tidal analysis results in Rashid & Tim paper (2007, Geophysical Research Letters) with the title of 'Tidal variability in the lower thermosphere: Comparison of Whole Atmosphere Model (WAM) simulations with observations from TIMED'.
The comparison indicates that the WAM (2017 version) performance in representing the tidal features is consistent with its performance in 2007 which has been validated against the TIMED observational dataset. 
The output of the latest operational WAM-IPE will be used to do the similar tidal analysis. 
And we feel confidence in the results given that we haven't done any large physics changes in WAM during the past 3 years.

**Comment by ZhuxiaoLi66** [comment]
![DE3_2_Rashid_paper](https://user-images.githubusercontent.com/22546571/93129235-ea4da480-f68d-11ea-92bd-725dad1b0e55.jpg)
![DE3_paper](https://user-images.githubusercontent.com/22546571/93129244-ee79c200-f68d-11ea-9743-f93b526b5be6.jpg)
![DW1_Rashid_paper](https://user-images.githubusercontent.com/22546571/93129271-f5083980-f68d-11ea-96e6-453d9b6cd259.jpg)
![SW2_paper](https://user-images.githubusercontent.com/22546571/93129290-fafe1a80-f68d-11ea-8085-f5253e90620f.jpg)

**Comment by ZhuxiaoLi66** [comment]
![T_116km_F150_tidal_analysis_anaual_3WV_runave](https://user-images.githubusercontent.com/22546571/93129567-74960880-f68e-11ea-837d-4d22471a1e32.png)
![U_95km_F150_tidal_analysis_anaual_3WV_runave](https://user-images.githubusercontent.com/22546571/93129572-78298f80-f68e-11ea-9ca7-100f5e1f5e2c.png)
![T_100km_F150_tidal_analysis_anaual_3WV_runave](https://user-images.githubusercontent.com/22546571/99290689-de03d600-27fb-11eb-8084-8b9e028dca22.png)

**Comment by ZhuxiaoLi66** [comment]
The data are processing now. and codes are revising.

**Comment by ZhuxiaoLi66** [comment]
some tidal data are produced on Hera:/scratch1/NCEPDEV/stmp2/Zhuxiao.Li/WAM_2013/
WAM_t_2013_229d_30d.dat
WAM_u_2013_229d_30d.dat
WAM_v_2013_229d_30d.dat
will be further processed today.

**Comment by ZhuxiaoLi66** [comment]
![tidal_analysis_example](https://user-images.githubusercontent.com/22546571/95909502-d4e69b80-0d5b-11eb-86a1-9b258195da88.png)

**Comment by ZhuxiaoLi66** [comment]
The above figure is a tidal analysis of WAM Temperature for January of 2013 with the variable input of solar parameters. 
Please compare it with the tidal analysis plot on our former WAM run with fixed values of F107 (150) and Kp(3) just above the current plot. you can find that the peak latitude positions of the temperature tides (DE3, DW1 and SW2) by the current run are quite consistent with those positions of the corresponding T tides by the old WAM run with fixed F107 and Kp input.

**Comment by ZhuxiaoLi66** [comment]
the long term (2013 all year long) data set (T at about 116km, T at 100km and U at 95km) are making (almost done), Hera now experiencing a halt, and it has happened many times during last weekend and this morning!
After I get the dataset, I will run the tidal analysis codes to get the year-long tidal analysis on these 3 dataset.

**Comment by ZhuxiaoLi66** [comment]
the dataset for 2013 has been made.

**Comment by ZhuxiaoLi66** [comment]
The following plots are the day-by-day tidal analysis results on T (100km & 116km) and U (95km) output of 2013 whole year by operational WAM. 
![T_116km_AMP_2013_opr_WAM](https://user-images.githubusercontent.com/22546571/99279573-9aa26b00-27ed-11eb-98b9-8a6fa6f97ff1.png)
![DE3_2_Rashid_paper](https://user-images.githubusercontent.com/22546571/99280046-26b49280-27ee-11eb-9205-8df014f7be96.jpg)

 https://user-images.githubusercontent.com/22546571/93129235-ea4da480-f68d-11ea-92bd-725dad1b0e55.jpg

**Comment by ZhuxiaoLi66** [comment]
![U_95km_AMP_2013_opr_WAM](https://user-images.githubusercontent.com/22546571/99280711-e1dd2b80-27ee-11eb-938e-043e5517dfa5.png)
![DE3_U_95km_Rashid_paper](https://user-images.githubusercontent.com/22546571/99281445-bd358380-27ef-11eb-9cb0-7ca5a42f6061.jpg)

**Comment by ZhuxiaoLi66** [comment]
![T_100km_AMP_2013_opr_DW1_SW2](https://user-images.githubusercontent.com/22546571/99281742-1d2c2a00-27f0-11eb-853a-e08a8e6893de.png)
![DW1_T_100km_paper_2](https://user-images.githubusercontent.com/22546571/99297528-9d10bf00-2805-11eb-8931-260d58089d98.jpg)

![SW2_T_100km_paper](https://user-images.githubusercontent.com/22546571/99282069-798f4980-27f0-11eb-8403-a3e83b30dadb.jpg)

**Comment by ZhuxiaoLi66** [comment]
[Tidal_analysis_2.pptx](https://github.com/NOAA-SWPC/GSMWAM-IPE/files/5638140/Tidal_analysis_2.pptx)

**Comment by ZhuxiaoLi66** [comment]
The above power point is about the tidal results comparison of the annual runs by the tip operational WAM (with the varying input parameters), 3-years-ago WAM version with fixed F10.7 (150) and Kp(3), 2008 WAM version with fixed F10.7 (150) and Kp(3) and the SABER observational data.

**Comment by ZhuxiaoLi66** [comment]
The following plots indicate the tidal analysis of our new test annual run for 2013 with varying input solar parameters and plusing 50. onto each F10.7 value. The results indicate the enlargement of F10.7 values makes the March DE3 amp peak much more significant.  
![T_116km_DE3_2013_f107_50](https://user-images.githubusercontent.com/22546571/101667216-48c7bc00-3a0c-11eb-9f54-f4fefae389e1.png)
![U_95km_DE3_2013_f107_50](https://user-images.githubusercontent.com/22546571/101667223-4c5b4300-3a0c-11eb-8ac6-86bebd2d9431.png)
![T_100km_DW1_SW2_2013_f107_50](https://user-images.githubusercontent.com/22546571/101667228-4f563380-3a0c-11eb-96cf-2b265e07fc96.png)

**Comment by timfullerrowell** [comment]
Thanks Zhuxiao,
Ummm, so increasing F10 actually makes the April/May peak stronger, rather
than weaker. I hoped there might be more dissipation with stronger F10
increasing the ion drag.

Maybe we need to run with identical conditions to the 2008 paper, Fixed F10
and Kp 150 and 3,
to see if it is the time dependence that makes the difference.

Tim

**Comment by ZhuxiaoLi66** [comment]
Thanks, Tim. will give it a try.

**Comment by ZhuxiaoLi66** [comment]
The following plots show the tidal analysis of the new annual run by the tip operational WAM with Fixed 107=150 and Kp=3. 
It seems that the March amplitude peaks for DE3 T (at 116km) and U(95km) move to summer (MJJ).
![T_116km_2013_F150_Kp3_opr](https://user-images.githubusercontent.com/22546571/102408299-9d3ddf00-3faa-11eb-8266-14f5485e6af7.png)
![U_95km_2013_F150_Kp3_opr](https://user-images.githubusercontent.com/22546571/102408314-a038cf80-3faa-11eb-84fa-eb985607abf2.png)
![T_100km_DW1_SW2_F150_Kp3_opr](https://user-images.githubusercontent.com/22546571/102408329-a464ed00-3faa-11eb-9475-e4cfcdb932ff.png)
