### ISSUE TITLE
wfs output check

### ISSUE THREAD

**Issue by ZhuxiaoLi66** [NOAA-SWPC/GSMWAM-IPE#52]

**Comment by ZhuxiaoLi66** [comment]
![T_20210504](https://user-images.githubusercontent.com/22546571/117216501-1bb1e680-adbd-11eb-8ce3-83c0a51d1da9.png)
![T_20210505](https://user-images.githubusercontent.com/22546571/117216506-1ce31380-adbd-11eb-876b-ecab11fc1c71.png)
![N2_20210505](https://user-images.githubusercontent.com/22546571/117216509-1d7baa00-adbd-11eb-92a2-d02a47904b64.png)
![N2_20210504](https://user-images.githubusercontent.com/22546571/117216511-1d7baa00-adbd-11eb-9e6c-666638628e17.png)
![O_20210505](https://user-images.githubusercontent.com/22546571/117216512-1e144080-adbd-11eb-832f-4911b03f29ff.png)
![O_20210504](https://user-images.githubusercontent.com/22546571/117216513-1e144080-adbd-11eb-8dc1-b384856d3aef.png)

**Comment by ZhuxiaoLi66** [comment]
The extreme values (Max, Min) of all variables in wfs output in the folder 20210504 seem reasonable and with a narrower range compared with 20210503 runs. The vertical velocity is within +- 100m/s.

**Comment by ZhuxiaoLi66** [comment]
Excuse me, all of the plots above indicate the variables at pressure level of 134 in WAM, at about 250km.

**Comment by ZhuxiaoLi66** [comment]
When I checked the wfs output on WCOSS  
/gpfs/dell2/ptmp/swpc.spacepara/pseudoops/wfs.20210503/12
I found some large vertical wind points near the top level at 70N lat accurred around 12Z and became mild after 1 hour and the model survived through this without any problem. 
The evolution of the W,  T, U at 11UT 12 and 13UT at the vertical section through 70N has been traced as following.
![W_70N_hgt_lon_2021050312UT](https://user-images.githubusercontent.com/22546571/117365333-62b2e100-ae7c-11eb-9658-013f52f4fded.png)
![W_70N_hgt_lon_2021050313UT](https://user-images.githubusercontent.com/22546571/117365490-95f57000-ae7c-11eb-849e-ac19e87361c6.png)

![U_W_T_70N_vertical_2021050311UT](https://user-images.githubusercontent.com/22546571/117365546-ac9bc700-ae7c-11eb-9616-f12d665f34a9.png)

![U_W_T_70N_vertical_2021050312UT](https://user-images.githubusercontent.com/22546571/117366039-6dba4100-ae7d-11eb-8f0e-aeeeb28c3f82.png)
![U_W_T_70N_vertical_2021050313UT](https://user-images.githubusercontent.com/22546571/117366055-73178b80-ae7d-11eb-8d46-22648c27ecd0.png)

**Comment by ZhuxiaoLi66** [comment]
The above plots are height_longitude plots, the color counter of the last 3 plots are Temperature and vectors indicate U & W. 
The W should be upward positive, right?

**Comment by twfang** [comment]
Thanks, Zhuxiao. Yes, Wn looks large. The model seems to be able to corp with the large perturbation and has been running stable now.

**Comment by timfullerrowell** [comment]
Thanks Zhuxiao,

Yes, W is positive up. These are driven by high latitude magnetospheric
forcing, rather than DA, so have been there in all the coupled model
validation studies with IPE, and IPE has been fine. I think the issue with
IPE is something else, and is probably not DA either. We will see.

Any news on Adam's run, Tzu-Wei? Can we breathe yet?
Tim
