### ISSUE TITLE
validation on WAM-IPE performance on WCOSS2 .vs. WCOSS 

### ISSUE THREAD

**Issue by ZhuxiaoLi66** [NOAA-SWPC/GSMWAM-IPE#59]

**Comment by ZhuxiaoLi66** [comment]
![neurtal_Temp_250km_WCOSS_WCOSS2_201303160600](https://user-images.githubusercontent.com/22546571/138170891-4baa3b2d-c395-46f2-965a-3330dfb3701d.png)

**Comment by ZhuxiaoLi66** [comment]
The above plot shows the Temp, diff after 6hr run of WAM-IPE. maybe something not match for the two runs, will double-check with the team.

**Comment by ZhuxiaoLi66** [comment]
![wcoss2_config_file](https://user-images.githubusercontent.com/22546571/138171367-36d64bb5-652b-4d47-92ec-6c88f98d7024.png)
![config_file_diff](https://user-images.githubusercontent.com/22546571/138171416-c306a5cb-e774-481a-8e9f-cf0e4fb93266.png)

**Comment by ZhuxiaoLi66** [comment]
![wcoss_config_file](https://user-images.githubusercontent.com/22546571/138171607-48a8408c-5ba0-4db6-902a-670be0a73e8b.png)

**Comment by akubaryk** [comment]
One is using "realtime" drivers when none exist (uses default values 24/7, same as fixderive), while the other uses "timeobs". These runs are not the same.

**Comment by ZhuxiaoLi66** [comment]
Thanks for the information, Adam. Will talk with you and Tzu-Wei later.

**Comment by ZhuxiaoLi66** [comment]
Please tell me how to do the 'match' run when you get time.

**Comment by akubaryk** [comment]
Use the same drivers for both, timeobs should work, or fixderive, or even realtime, but they need to be the same.

**Comment by ZhuxiaoLi66** [comment]
Good catch, thanks. excuse me for not really checking on the difference, rushed into some other things just now.

**Comment by ZhuxiaoLi66** [comment]
The following plot is an update of the one posted yesterday after applying the right branch and running mode.  It seems the difference (after 6 hrs) is pretty mild compared with the compiler changing test before. 

![neurtal_Temp_250km_WCOSS_WCOSS2_201303160600](https://user-images.githubusercontent.com/22546571/138345025-0cfb2b21-7e2a-4531-a706-433bd9da51f3.png)
