### ISSUE TITLE
Change Fixed Height Grid To Match IPE levels

### ISSUE THREAD

**Issue by oehmke** [NOAA-SWPC/GSMWAM-IPE#6]
The group would like to experiment with changing the fixed height grid that is used in the mediator to regrid from WAM to IPE. The idea is to switch the heights of that grid to match the IPE levels to see how that affects the behavior of the coupled system.

**Comment by twfang** [comment]
@rmontuoro have we addressed this issue with WAM-IPE v1.0?

**Comment by rmontuoro** [comment]
@twfang, this issue was resolved with NEMS commit [99db77c](https://github.com/NOAA-SWPC/NEMS/commit/99db77c9345e5eecd86c5445196ca8238f8e22c1)
