### ISSUE TITLE
improperly set FHOUT/IPEFREQ can trickle through on restart runs

### ISSUE THREAD

**Issue by akubaryk** [NOAA-SWPC/GSMWAM-IPE#63]
@ZhuxiaoLi66 pointed out this issue where FHMAX is used verbatim on restart runs to check the validity of IPEFREQ and FHOUT; it has been rectified in `bugfix/fhmax_restart` and will be merged.

**Comment by ZhuxiaoLi66** [comment]
Thanks, Adam!
