### ISSUE TITLE
global mean neutral density product plot for 3day solar wind driven + 3day Kp forecast driven  

### ISSUE THREAD

**Issue by ZhuxiaoLi66** [NOAA-SWPC/GSMWAM-IPE#74]

**Comment by ZhuxiaoLi66** [comment]
![DEN_xy_opr_20150311_0316_obs_forecast](https://user-images.githubusercontent.com/22546571/216419049-6a819aba-613b-45ba-866d-c6a5cc432c5e.png)
![DEN_xy_opr_20150313_0319_obs_forecast](https://user-images.githubusercontent.com/22546571/216419083-fbc47830-62d0-41d9-87c8-5f0e76cfdbb7.png)
![DEN_xy_opr_20150316_0321_obs_forecast](https://user-images.githubusercontent.com/22546571/216419118-34a93f37-0bf4-436a-9e34-1c6d71ac85f3.png)

**Comment by ZhuxiaoLi66** [comment]
![DEN_xy_opr_20150317_18UT_3days_CONOUP1_CONOUP2](https://user-images.githubusercontent.com/22546571/218186714-7131634e-cdf5-457a-8fc2-622ce4daf82f.png)
![DEN_xy_opr_20150317_18UT_3days_CONOUP1_CONOUP2_obs_driven_2](https://user-images.githubusercontent.com/22546571/218186751-3f0d6076-021b-486e-966d-a98a775478a2.png)

**Comment by ZhuxiaoLi66** [comment]
Tim, the above two plots are our test scheme plots to show the advantage of CONOUP2 run over CONOUP1 run during storm time.  As discussed, the current time is 18UT of Mar.17 indicated by the gray vertical line. its right side is the WAM-IPE forecasts.
The left side is the nowcast+analysis simulations with obs data kicked in.  the red line is the CONOUPS2 with the obs KP and obs SW variables before and at 18UT, and the blue line is the CONOUPS1 with the obs KP only. the forecast part after 18UT shows the CONOUPS2 falling down to CONOUPS1 without the obs SW. both the KP and SW here are supposed to be forecasted variables. I add the black dashed curve line showing the run with both the obs KP and SW after 18UT which looks as the real fact (goal) and how well CONOUPS2 can catch it against CONOUPS1.   please tell me your feel and idea about the plots.

**Comment by timfullerrowell** [comment]
Thanks Zhuxiao,

Definitely on the right track.

Suggestions:
1.  Cut the red line after the real-time on CONOPS2.
2. Continue the blue line where the red line is now in the forecast.
3. Spelling CONOPS1 CONOPS2
4 Change caption to CONOP1 - perfect forecast
4. Can we add a line for a: CONOPS1 - realistic forecast
For this line can you make up a line like the blue line, where it doesn't
follow the response at all and captures only about half the response of the
perfect Kp

**Comment by ZhuxiaoLi66** [comment]
Tim & Tzu-Wei, the updated version of the CONOPS1 & 2 performance plot for the 2015 St. Patrick storm is here. Tim, I make the 'current time' line explained in the regular legend box, which will make it less confusing.

![DEN_xy_opr_20150317_18UT_3days_CONOPS12_6lines_legend](https://user-images.githubusercontent.com/22546571/219464881-cc6b9e6c-29c7-4d5a-9c3e-1de331c5706a.png)
