### ISSUE TITLE
CCMC neutal density product validation

### ISSUE THREAD

**Issue by ZhuxiaoLi66** [NOAA-SWPC/GSMWAM-IPE#75]
The neutral density product data files for Feb.3 2022 storm delivered by CCMC have been checked. The comparison plots with our original product files are posted for further discussion and record.

**Comment by ZhuxiaoLi66** [comment]
![DEN_CCMC_250km_4p_20220203](https://user-images.githubusercontent.com/22546571/222539842-a74f6c75-1423-4488-b6b0-47d38057f6a1.png)
![DEN_product_250km_4p_20220203](https://user-images.githubusercontent.com/22546571/222539866-34352afc-5641-4022-ac3f-b7082555b715.png)
![DEN_CCMC_400km_4p_20220203](https://user-images.githubusercontent.com/22546571/222539882-982aeda6-2417-4525-a969-b5eac93a7e2c.png)
![DEN_product_400km_4p_20220203](https://user-images.githubusercontent.com/22546571/222539919-5abdf420-3e57-4c37-9536-8f6e4b00934d.png)
![DEN_CCMC_800km_4p_20220203](https://user-images.githubusercontent.com/22546571/222539975-0a3de94f-b05e-4a4c-a1b0-917c2b74973d.png)
![DEN_product_800km_4p_20220203](https://user-images.githubusercontent.com/22546571/222540007-04d95ea7-5c31-4fd3-b3bc-0dccfd954cd3.png)
![DEN_CCMC_1000km_4p_20220203](https://user-images.githubusercontent.com/22546571/222540063-4123558a-a14c-4a30-ab3b-89453d7d7281.png)
![DEN_product_1000km_4p_20220203](https://user-images.githubusercontent.com/22546571/222540109-4f45e512-f921-4f17-90e5-30b02499ef78.png)
![DEN_CCMC_800km_24p_20220203](https://user-images.githubusercontent.com/22546571/222540171-559d9b32-0e0a-42ba-94e0-48aab951e3dd.png)
![DEN_product_800km_24p_20220203](https://user-images.githubusercontent.com/22546571/222540243-2245e874-aaa0-4594-a158-091d5791a174.png)
![DEN_CCMC_400km_24p_20220203](https://user-images.githubusercontent.com/22546571/222540295-151e47ff-3019-4c35-950f-357a6ca2a7ce.png)
![DEN_product_400km_24p_20220203](https://user-images.githubusercontent.com/22546571/222540340-72bddb66-f46b-4803-83ec-eda3b1b53b66.png)
![DEN_CCMC_600km_4p_20220203](https://user-images.githubusercontent.com/22546571/222540389-5b8ee77f-5b74-42ef-890f-ec5036b34ecf.png)
![DEN_product_600km_4p_20220203](https://user-images.githubusercontent.com/22546571/222540412-ded20665-0663-4fb4-b594-70dad87b90b8.png)

**Comment by ZhuxiaoLi66** [comment]
Hi All, would like to tell you some good news, after I revised my Fortran code and let it do the neutral density expolation since WAM Level 149, which means excluding Level 150 for the interpolation, the results become very close to CCMC data with Adam's package. In conclusion, now I think we shouldn't have any concerns about the neutral density product from CCMC.
Would like to post the plots for the new result at 800km here, also attached the CCMC plots for comparison.

![DEN_product_L149_800km_4p_20220203](https://user-images.githubusercontent.com/22546571/222820633-852615ca-2f23-417e-8f55-b1a394e50834.png)
![DEN_CCMC_800km_4p_20220203](https://user-images.githubusercontent.com/22546571/222820682-83ca163f-f075-41f2-85a7-6b0f95118bee.png)
![DEN_product_L149_800km_24p_20220203](https://user-images.githubusercontent.com/22546571/222820732-65cfa3d3-9814-45d6-8442-c16fd915af52.png)
![DEN_CCMC_800km_24p_20220203](https://user-images.githubusercontent.com/22546571/222820809-08d6b18f-7c7d-409b-a5fb-0e23c2e6714d.png)

**Comment by ZhuxiaoLi66** [comment]
The following plots are the density difference (CCMC-product) ratio to the neutral product [(CCMC-product)/product]. larger along the altitude, I think they are small enough even for 800km. 
![DEN_diff_perc_CCMC_product_250km_4p_20220203](https://user-images.githubusercontent.com/22546571/224136416-6268b450-2d44-441e-86f2-3eae083ebdf6.png)
![DEN_diff_perc_CCMC_product_400km_4p_20220203](https://user-images.githubusercontent.com/22546571/224136436-e398d9c9-7260-403d-9ab4-4457c26afee5.png)
![DEN_diff_perc_CCMC_product_800km_4p_20220203](https://user-images.githubusercontent.com/22546571/224136458-c1a4d38e-42f6-4f35-a083-61648863e68c.png)

**Comment by ZhuxiaoLi66** [comment]
The other thing I found in CCMC files is that the unit of the neutral density is "m^-3", which should be "kg*m^-3".  since the formal name of the variable is "thermosphere_mass_density".

**Comment by twfang** [comment]
Thanks for catching that Zhuxiao.

**Comment by akubaryk** [comment]
> The other thing I found in CCMC files is that the unit of the neutral density is "m^-3", which should be "kg*m^-3". since the formal name of the variable is "thermosphere_mass_density".

A fix has been pushed to address this.

**Comment by ZhuxiaoLi66** [comment]
@akubaryk nice to know, thanks.
