### ISSUE TITLE
TEC of opr WAM-IPE & its opr bias ratio against GloTEC checking for period of storm Apr.24 this week 

### ISSUE THREAD

**Issue by ZhuxiaoLi66** [NOAA-SWPC/GSMWAM-IPE#79]
The new parameter set (skeddy0=70, skeddy_semiann=-10) of eddy mixing has been applied to the operational WAM-IPE for about 2 weeks. The recent operational TEC bias ratio plots (by daily email) have been monitored closely, it has been found that the bias ratio began to climb up from Apr.21, while there is a sudden jump up on the latest storm day of Apr.24 2023, from 0.8 to about 1.2, the ratio jumped back to about 0.8 on the day after, Apr.25.   
With Tim's suggestion, I checked the TEC maps of opr WAM-IPE and GloTEC separately and have done some comparisons to seek the reason for the sudden jump in the bias ratio on Apr.24, and give a further investigation of the TEC performance of both of the opr WAM-IPE and the opr GloTEC.         
On the other hand, the free WAM-IPE annual run with the new parameters is extended to the current time to get a baseline for the operational performance after the parameter reset.

**Comment by ZhuxiaoLi66** [comment]
The following plot is the recent bias ratio performance of the opr WAM-IPE against GloTEC. 
![daily_TEC_bias_ratio_WAM-IPE_GloTEC_20230428](https://user-images.githubusercontent.com/22546571/235248448-1d0a80cb-74f4-471d-ad40-e0bb8fcdde6b.png)
Let us put the jump aside and pay attention to the recent ratios after the parameter-set change.  The new parameter is supposed to kick in after about 10-20 days. so far it seems that the ratio has not changed much before and after the reset of parameters. In theory, we think it is acceptable so far. 
based on the formula of semiannual variation, on Mar.21 and Sep.21 (Equinox) the skeddy arrive at its 'minimum'. 
For the new eddy parameters, skeddy = 70- (-10) = 80
For the original eddy parameters, skeddy = 140 - 60 = 80
So in theory, the skeddy is the same at Equinox, the following former validation figure shows that the ratio should increase a little bit after that. 
![bias_ratio_dayno_para5_20221214_CONOPS12_std](https://user-images.githubusercontent.com/22546571/235251496-3086eb37-f67a-4e9b-91e9-f0e88c5a31d7.png)
we will have a close eye on the ratio change hereafter.

**Comment by ZhuxiaoLi66** [comment]
Now let us go back to the TEC & bias ratio checking for the period of Apr.20-Apr.25, especially paying attention to the bias ratio jump on Apr. 24. 
The following are the TEC maps of operational WAM-IPE during this period. 
![TEC_wfs_20230420_6hrly](https://user-images.githubusercontent.com/22546571/235253672-19041f42-bba8-4e8a-838d-130acf94958e.png)
![TEC_wfs_20230421_6hrly](https://user-images.githubusercontent.com/22546571/235253674-32c0ff41-a452-43e6-9a9e-e47e59c14840.png)
![TEC_wfs_20230422_6hrly](https://user-images.githubusercontent.com/22546571/235253677-454e9956-dbfb-4ef5-8495-a242bceac4dc.png)
![TEC_wfs_20230423_6hrly](https://user-images.githubusercontent.com/22546571/235253680-0da05ab9-7fa3-4a3b-b172-5f6bc8224218.png)
![TEC_wfs_20230424_6hrly](https://user-images.githubusercontent.com/22546571/235253682-036a5c34-b348-4e04-9aeb-aec1a76b6418.png)
![TEC_wfs_20230425_6hrly](https://user-images.githubusercontent.com/22546571/235253684-ede716f8-19d6-44a2-a736-e2c2f7d2fb58.png)

**Comment by ZhuxiaoLi66** [comment]
This section shows the GloTEC maps (30mins time window method) of the area with the quality flag values equal to or above 4. 
They are the area where we define more effective & valid and use them to calculate the opr bias ratio values.

![TEC_glotec_20230420_6hrly](https://user-images.githubusercontent.com/22546571/235254742-973b1f88-f4ee-43b3-8764-5bb2bd88a51a.png)
![TEC_glotec_20230421_6hrly](https://user-images.githubusercontent.com/22546571/235254743-1f504a4b-b14f-424f-8a90-0d9945d575e4.png)
![TEC_glotec_20230422_6hrly](https://user-images.githubusercontent.com/22546571/235254744-a0459370-283c-46e9-8708-a606686332a6.png)
![TEC_glotec_20230423_6hrly](https://user-images.githubusercontent.com/22546571/235254745-0c939276-1489-4036-90de-cbc27d165257.png)
![TEC_glotec_20230424_6hrly](https://user-images.githubusercontent.com/22546571/235254746-385bf9cb-8167-4625-bd72-c3b0a8a9038d.png)
![TEC_glotec_20230425_6hrly](https://user-images.githubusercontent.com/22546571/235254750-376f4c0d-fb60-4efb-b7aa-63424be321c9.png)

**Comment by ZhuxiaoLi66** [comment]
For getting a general view & whole picture of the GloTEC data and having a further pattern comparison with the opr WAM-IPE TEC, I used all of the GloTEC data without the quality flag filter, to get the following GloTEC maps for this period.
![TEC_glotec_all_flag_20230420_6hrly](https://user-images.githubusercontent.com/22546571/235255461-194965a3-7a00-4956-a561-b35f9a1e10db.png)
![TEC_glotec_all_flag_20230421_6hrly](https://user-images.githubusercontent.com/22546571/235255464-564f957e-0ed4-425a-8189-1bcdf14690a0.png)
![TEC_glotec_all_flag_20230422_6hrly](https://user-images.githubusercontent.com/22546571/235255471-15d6f811-0f0b-488f-8cd9-baf99c1302af.png)
![TEC_glotec_all_flag_20230423_6hrly](https://user-images.githubusercontent.com/22546571/235255472-b2a9e40d-38f7-458b-bc9f-1ed8a7777b17.png)
![TEC_glotec_all_flag_20230424_6hrly](https://user-images.githubusercontent.com/22546571/235255476-8775441c-3834-4d30-a2ce-925ba26406d5.png)
![TEC_glotec_all_flag_20230425_6hrly](https://user-images.githubusercontent.com/22546571/235255478-eced782a-cb5b-4435-8469-08221d34cfd4.png)

**Comment by ZhuxiaoLi66** [comment]
The following re-arranged plots for TEC comparison between WFS, all GloTEC, quality-flag filtered GloTEC (more reliable) are helpful for further investigation, especially give us a detailed idea about the performance of both opr WAM-IPE and GloTEC, and the reason why the bias ratio jumped up on the storm day of Apr.24.
![TEC_wfs_glotec_all_flag_3P_20230423](https://user-images.githubusercontent.com/22546571/235258611-5fa1fdc9-6a67-44dc-9e75-70e498ccc650.png)

![TEC_wfs_glotec_all_flag_3P_20230424](https://github.com/NOAA-SWPC/GSMWAM-IPE/assets/22546571/f47ac802-9246-4c73-a2f6-d7277fa9f9c9)

![TEC_wfs_glotec_all_flag_3P_20230425](https://user-images.githubusercontent.com/22546571/235258642-fbbf3586-cf70-405a-aee1-e588e214808a.png)

**Comment by ZhuxiaoLi66** [comment]
The following plots for the other 3 days(Apr.22, 21, 20) when are relatively quiet before the storm, maybe will check some other days e.g. Apr.17 and Apr.18 for more quiet time later.
Please pay attention to the GloTEC maps of Apr.20 (last plot), it seems that the data is on the wrong map, I mean the longitude should switch 180 degrees. This happened before. Since I use the same code for calculations and plotting for all these days, so should be a problem with the GloTEC data itself. 
  
![TEC_wfs_glotec_all_flag_3P_20230422](https://user-images.githubusercontent.com/22546571/235259657-dbab6251-76e3-4741-849a-85594f9fcb05.png)
![TEC_wfs_glotec_all_flag_3P_20230421](https://user-images.githubusercontent.com/22546571/235259670-88fd9619-98cb-4d15-85ac-8433cdf5154c.png)
![TEC_wfs_glotec_all_flag_3P_20230420](https://user-images.githubusercontent.com/22546571/235259685-1422cf9a-75d9-4792-b1e7-1ab04765940d.png)

**Comment by ZhuxiaoLi66** [comment]
Any comments on this checking are welcome. 
![Screenshot from 2023-07-06 12-21-51](https://github.com/NOAA-SWPC/GSMWAM-IPE/assets/22546571/6ede1332-7a47-491a-b53b-664872db2cd0)

**Comment by twfang** [comment]
@ZhuxiaoLi66 The jump is associated with the geomagnetic storm, I don't think that's where the issue is. We want to make sure our ratio doesn't continue to decrease for the quiet days. The GloTEC plot on 4/20 looks wrong. The TEC distribution doesn't look right. Could you please double-check?

**Comment by ZhuxiaoLi66** [comment]
Tzu-Wei, thanks for looking about this. We are checking the both issues now, it seems that WAM-IPE overestimates TEC during the storm time, will check some other events to clarify this. And yes, we are keeping a close eye on the tendency of the quite days ratios. Based on our free WAM-IPE annual run with the new parameters, the ratios should mildly goes up somewhat recently. you are right, the 4/20 maps looks wrong. I also notice that, please have a look at my comments with the last plots. After the double check, I think there is something wrong with the saving of the operational GloTEC data that day, the longitude seems needs to switch 180 degree. This happened before, will send an e-mail to Dom to discuss about it.

**Comment by ZhuxiaoLi66** [comment]
![TEC_30min_bias_ratio_opr_202304](https://user-images.githubusercontent.com/22546571/236303027-7cfd0c30-986b-43c8-836f-fd6c4978fe9b.png)

**Comment by ZhuxiaoLi66** [comment]
![daily_TEC_bias_ratio_WAM-IPE_GloTEC](https://user-images.githubusercontent.com/22546571/236303211-2441ecf6-e966-4085-84b0-e71dadfec961.png)

**Comment by ZhuxiaoLi66** [comment]
![Screenshot from 2023-07-06 12-21-51](https://github.com/NOAA-SWPC/GSMWAM-IPE/assets/22546571/aef1e1a8-b5a2-482f-ac61-218a360f53ee)
