### ISSUE TITLE
Drivers: update realtime solar/geomagnetic forcing input to use solar wind and ovation parameters

### ISSUE THREAD

**Issue by akubaryk** [NOAA-SWPC/GSMWAM-IPE#9]
Need to find where these files are on WCOSS and then write processing scripts to get them into the model for INPUT_PARAMETERS=realtime in the same way that the post-processed input files are parsed (INPUT_PARAMETERS=timeobs).

**Comment by twfang** [comment]
Adam, is this issue solved?

**Comment by akubaryk** [comment]
I don't think we can mark this resolved until we have a solution to the data gaps, unless we want to open a separate issue for that. GSMWAM-IPE/develop doesn't have the changes to parse.py for the realtime drivers, either.

**Comment by twfang** [comment]
Agreed.

**Comment by akubaryk** [comment]
realtime_input_parameters branch has been created, we have a robust strategy for handling gaps in the data, and this will be open for a pull when #44 is complete.
